[mypy]
# Global settings
python_version = 3.10
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True

# Per-module settings
[mypy-selenium.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-webdriver_manager.*]
ignore_missing_imports = True

[mypy-streamlit.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-bs4.*]
ignore_missing_imports = True

[mypy-schedule.*]
ignore_missing_imports = True
